#!/bin/bash
# =============================================================================
# run_once_09-material-you.sh
# Run once by chezmoi (re-runs if this file changes)
# "Material You / follows-the-wallpaper" — module separate from the rest of the dotfiles.
#
# This module makes the desktop (kitty, btop, prompt) follow the wallpaper
# colors, relying on kde-material-you-colors (which regenerates on every
# wallpaper change).
#
# Deploys:
#   - dot_local/bin/kitty-material-you.py / btop-material-you.py / hook
#   - dot_local/bin/zed-material-you.py  (Zed theme "Material You")
#   - dot_config/kitty/kitty.conf        (includes theme-wallpaper.conf)
#   - dot_config/btop/btop.conf          (color_theme = materialyou)
#   - the _prompt_material block in ~/.zshrc  (already handled via dot_zshrc)
# Here we impose the daemon config (config.conf is rewritten by the daemon -> we
# do not version the file, we set the key only):
#   - on_change_hook              -> recolors kitty/btop/zed
# =============================================================================
set -e

source "${CHEZMOI_SOURCE_DIR:-$HOME/.local/share/chezmoi}/.lib_logging.sh"

MYC_CFG="$HOME/.config/kde-material-you-colors/config.conf"
HOOK="$HOME/.local/bin/kitty-material-you-hook.sh"
ZS="$HOME/.config/zed/settings.json"

# --- 1) Enable the hook in kde-material-you-colors ---------------------------
if command -v kde-material-you-colors >/dev/null 2>&1; then
  if [ -f "$MYC_CFG" ]; then
    if grep -q "on_change_hook=$HOOK" "$MYC_CFG" 2>/dev/null; then
      log_skip "on_change_hook already configured"
    else
      sed -i "s|^on_change_hook=.*|on_change_hook=$HOOK|" "$MYC_CFG"
      log_pass "on_change_hook -> $HOOK"
    fi
  else
    log_warn "kde-material-you-colors config missing ($MYC_CFG) — create the folder"
    mkdir -p "$(dirname "$MYC_CFG")"
    printf '[CUSTOM]\non_change_hook=%s\n' "$HOOK" > "$MYC_CFG"
  fi

  # restart the daemon to pick up the hook
  kde-material-you-colors --stop >/dev/null 2>&1 || true
  sleep 1
  nohup /usr/bin/kde-material-you-colors >/dev/null 2>&1 &
  log_info "kde-material-you-colors daemon restarted"
else
  log_warn "kde-material-you-colors not installed — install via AUR"
fi

# --- 2) kitty: make sure the theme-wallpaper.conf include is present ----------
KC="$HOME/.config/kitty/kitty.conf"
if [ -f "$KC" ] && ! grep -q 'theme-wallpaper.conf' "$KC"; then
  printf '\ninclude theme-wallpaper.conf\n' >> "$KC"
  log_pass "include theme-wallpaper.conf added to kitty.conf"
else
  log_skip "kitty.conf already includes theme-wallpaper.conf"
fi

# --- 3) generate kitty + btop + zed + prompt a first time --------------------
log_info "Initial generation of kitty + btop + zed + prompt..."
python3 "$HOME/.local/bin/kitty-material-you.py" || true
python3 "$HOME/.local/bin/btop-material-you.py" || true
python3 "$HOME/.local/bin/zed-material-you.py" || true
python3 "$HOME/.local/bin/material-you-prompt.py" || true

# --- 4) Zed: point settings.json at the "Material You" theme ------------------
# The theme itself follows the wallpaper (regenerated by zed-material-you.py); here
# we just make sure Zed has the theme selected. settings.json is rewritten
# dynamically by Zed (agent permissions) -> we do not version it, we set the
# single key we care about, without touching the rest.
if [ -f "$ZS" ]; then
  if grep -q '"theme": "Material You"' "$ZS" || grep -q '"dark": "Material You"' "$ZS"; then
    log_skip "Zed theme already on \"Material You\""
  elif grep -q '"theme": {' "$ZS"; then
    # Recent Zed writes the key as an object {mode, light, dark}; the custom theme
    # has no light/dark variants, so point both at it.
    sed -i 's/"light": "[^"]*"/"light": "Material You"/; s/"dark": "[^"]*"/"dark": "Material You"/' "$ZS"
    log_pass "Zed theme -> Material You (light/dark)"
  elif grep -q '"theme"' "$ZS"; then
    sed -i 's/"theme": "[^"]*"/"theme": "Material You"/' "$ZS"
    log_pass "Zed theme -> Material You"
  else
    log_warn "key \"theme\" missing from $ZS (Zed will set it itself)"
  fi
else
  printf '{\n  "theme": "Material You"\n}\n' > "$ZS"
  log_pass "Zed settings.json created (Material You theme)"
fi

log_pass "material-you module configured."
